// 38 Real Employees from Excel Master
export interface SeedEmployee {
  id: string;
  employee_id_code: string;
  first_name: string;
  last_name: string;
  gender: string;
  nationality: string;
  date_of_birth: string;
  mobile_number: string;
  email: string;
  departments: { name: string };
  designations: { title: string };
  reporting_manager?: string;
  date_of_joining: string;
  employment_type?: string;
  qid_passport_no?: string;
  id_expiry_date?: string;
  basic_salary: number;
  hra: number;
  tra: number;
  other_allowances: number;
  benefit_telephone?: string;
  benefit_accommodation?: string;
  benefit_vehicle?: string;
  bank_name?: string;
  iban?: string;
  air_ticket?: string;
  air_ticket_fare_cap?: number;
  employee_status: string;
  emergency_contact_name?: string;
  relation_with_employee?: string;
  emergency_contact_no?: string;
  remarks?: string;
}

export const REAL_EMPLOYEES_SEED: any[] = [
  {
    "id": "emp-seed-1",
    "employee_id_code": "EMP-001",
    "first_name": "Jithin",
    "last_name": "Abdul Latheef",
    "gender": "Male",
    "nationality": "India",
    "date_of_birth": "1988-09-06",
    "mobile_number": "74053716",
    "email": "jithin.abdullatheef@company.qa",
    "departments": {
      "name": "Finance and Operations"
    },
    "designations": {
      "title": "General Manager"
    },
    "reporting_manager": "",
    "date_of_joining": "2016-03-16",
    "employment_type": "Full-Time",
    "qid_passport_no": "28835629905",
    "id_expiry_date": "2027-02-24",
    "basic_salary": 11400.0,
    "hra": 0.0,
    "tra": 4000.0,
    "other_allowances": 2100.0,
    "benefit_telephone": "Provided By Company",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "QA45CBQA000000004700659515101",
    "air_ticket": "Yearly",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-2",
    "employee_id_code": "EMP-002",
    "first_name": "Shajid",
    "last_name": "Varikkodath",
    "gender": "Male",
    "nationality": "India",
    "date_of_birth": "1980-05-27",
    "mobile_number": "33263045",
    "email": "shajid.varikkodath@company.qa",
    "departments": {
      "name": "HR and Admin"
    },
    "designations": {
      "title": "Admin Manager"
    },
    "reporting_manager": "",
    "date_of_joining": "2009-02-19",
    "employment_type": "Full-Time",
    "qid_passport_no": "28035626152",
    "id_expiry_date": "2027-02-16",
    "basic_salary": 7200.0,
    "hra": 0.0,
    "tra": 2500.0,
    "other_allowances": 1300.0,
    "benefit_telephone": "Provided By Company",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "QA38CBQA000000004010468348001",
    "air_ticket": "Yearly",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-3",
    "employee_id_code": "EMP-003",
    "first_name": "Mohamed",
    "last_name": "Farhan Abdul Salam",
    "gender": "Male",
    "nationality": "India",
    "date_of_birth": "1995-02-28",
    "mobile_number": "51496949",
    "email": "mohamed.farhanabdulsalam@company.qa",
    "departments": {
      "name": "Marketing"
    },
    "designations": {
      "title": "Marketing Manager"
    },
    "reporting_manager": "",
    "date_of_joining": "2023-12-04",
    "employment_type": "Full-Time",
    "qid_passport_no": "29535627305",
    "id_expiry_date": "2028-01-14",
    "basic_salary": 6000.0,
    "hra": 0.0,
    "tra": 2000.0,
    "other_allowances": 1000.0,
    "benefit_telephone": "Provided By Company",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "QA29CBQA000000004730618867101",
    "air_ticket": "Yearly",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-4",
    "employee_id_code": "EMP-004",
    "first_name": "Mohamed",
    "last_name": "Shafraz Hussain",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1979-10-26",
    "mobile_number": "33242454",
    "email": "mohamed.shafrazhussain@company.qa",
    "departments": {
      "name": "Admin"
    },
    "designations": {
      "title": "Maintenance Manager"
    },
    "reporting_manager": "",
    "date_of_joining": "2015-03-15",
    "employment_type": "Full-Time",
    "qid_passport_no": "27914414032",
    "id_expiry_date": "2027-04-12",
    "basic_salary": 4000.0,
    "hra": 0.0,
    "tra": 1500.0,
    "other_allowances": 500.0,
    "benefit_telephone": "Provided By Company",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "QA72CBQA000000004610487455001",
    "air_ticket": "Yearly",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-5",
    "employee_id_code": "EMP-005",
    "first_name": "Muthira",
    "last_name": "Kulangara Mohamed Hashim",
    "gender": "Male",
    "nationality": "India",
    "date_of_birth": "1974-07-07",
    "mobile_number": "55407477",
    "email": "muthira.kulangaramohamedhashim@company.qa",
    "departments": {
      "name": "Admin"
    },
    "designations": {
      "title": "PRO"
    },
    "reporting_manager": "",
    "date_of_joining": "2007-09-26",
    "employment_type": "Full-Time",
    "qid_passport_no": "27435600433",
    "id_expiry_date": "2026-09-23",
    "basic_salary": 3100.0,
    "hra": 0.0,
    "tra": 1000.0,
    "other_allowances": 600.0,
    "benefit_telephone": "Provided By Company",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "QA39CBQA000000004010468425001",
    "air_ticket": "Yearly",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-6",
    "employee_id_code": "EMP-006",
    "first_name": "Jay",
    "last_name": "Alva Cadag",
    "gender": "Male",
    "nationality": "Philippines",
    "date_of_birth": "1970-12-10",
    "mobile_number": "77479716",
    "email": "jay.alvacadag@company.qa",
    "departments": {
      "name": "Admin"
    },
    "designations": {
      "title": "Admin Assistant"
    },
    "reporting_manager": "",
    "date_of_joining": "2021-02-01",
    "employment_type": "Full-Time",
    "qid_passport_no": "27060811070",
    "id_expiry_date": "2026-12-25",
    "basic_salary": 2300.0,
    "hra": 0.0,
    "tra": 800.0,
    "other_allowances": 400.0,
    "benefit_telephone": "Provided By Company",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710016731083",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-7",
    "employee_id_code": "EMP-007",
    "first_name": "Narayanan",
    "last_name": "Bahadur Khawas",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1973-11-24",
    "mobile_number": "55693648",
    "email": "narayanan.bahadurkhawas@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "A/c Teachnician"
    },
    "reporting_manager": "",
    "date_of_joining": "2006-01-27",
    "employment_type": "Full-Time",
    "qid_passport_no": "27352405197",
    "id_expiry_date": "2027-01-24",
    "basic_salary": 2900.0,
    "hra": 0.0,
    "tra": 1000.0,
    "other_allowances": 800.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790049496925",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-8",
    "employee_id_code": "EMP-008",
    "first_name": "Raghunath",
    "last_name": "Balami",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1979-04-07",
    "mobile_number": "77455386",
    "email": "raghunath.balami@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "A/c Teachnician"
    },
    "reporting_manager": "",
    "date_of_joining": "2009-02-06",
    "employment_type": "Full-Time",
    "qid_passport_no": "27952421293",
    "id_expiry_date": "2027-02-03",
    "basic_salary": 1800.0,
    "hra": 0.0,
    "tra": 800.0,
    "other_allowances": 400.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790028627490",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-9",
    "employee_id_code": "EMP-009",
    "first_name": "Ajay",
    "last_name": "Kumar Chaudhay",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1991-10-20",
    "mobile_number": "33816580",
    "email": "ajay.kumarchaudhay@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "A/c Teachnician"
    },
    "reporting_manager": "",
    "date_of_joining": "2015-02-23",
    "employment_type": "Full-Time",
    "qid_passport_no": "29152429045",
    "id_expiry_date": "2027-02-20",
    "basic_salary": 1850.0,
    "hra": 0.0,
    "tra": 800.0,
    "other_allowances": 400.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790022336254",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-10",
    "employee_id_code": "EMP-010",
    "first_name": "Angira",
    "last_name": "Chaudhary",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1988-12-21",
    "mobile_number": "71319559",
    "email": "angira.chaudhary@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "A/c Teachnician"
    },
    "reporting_manager": "",
    "date_of_joining": "2025-02-11",
    "employment_type": "Full-Time",
    "qid_passport_no": "28852463005",
    "id_expiry_date": "2027-02-10",
    "basic_salary": 1260.0,
    "hra": 0.0,
    "tra": 500.0,
    "other_allowances": 340.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790012985656",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-11",
    "employee_id_code": "EMP-011",
    "first_name": "Devaraj",
    "last_name": "Khawas",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1982-07-13",
    "mobile_number": "70409811",
    "email": "devaraj.khawas@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2005-09-17",
    "employment_type": "Full-Time",
    "qid_passport_no": "28252409655",
    "id_expiry_date": "2026-09-12",
    "basic_salary": 1290.0,
    "hra": 0.0,
    "tra": 500.0,
    "other_allowances": 360.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710016727313",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-12",
    "employee_id_code": "EMP-012",
    "first_name": "Hari",
    "last_name": "Chandra Khawas",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1984-10-19",
    "mobile_number": "50196569",
    "email": "hari.chandrakhawas@company.qa",
    "departments": {
      "name": "Driver"
    },
    "designations": {
      "title": "Driver cum painter"
    },
    "reporting_manager": "",
    "date_of_joining": "2005-09-15",
    "employment_type": "Full-Time",
    "qid_passport_no": "28452406501",
    "id_expiry_date": "2026-09-12",
    "basic_salary": 1680.0,
    "hra": 0.0,
    "tra": 700.0,
    "other_allowances": 420.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790045233686",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-13",
    "employee_id_code": "EMP-013",
    "first_name": "Mohamed",
    "last_name": "Ashar Ibrahim",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1983-08-07",
    "mobile_number": "33340660",
    "email": "mohamed.asharibrahim@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Driver cum Plumber"
    },
    "reporting_manager": "",
    "date_of_joining": "2011-12-27",
    "employment_type": "Full-Time",
    "qid_passport_no": "28314410603",
    "id_expiry_date": "2026-12-26",
    "basic_salary": 2100.0,
    "hra": 0.0,
    "tra": 800.0,
    "other_allowances": 600.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710018520096",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-14",
    "employee_id_code": "EMP-014",
    "first_name": "Mohamed",
    "last_name": "Faslee Mohamed Nawfer",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1979-03-18",
    "mobile_number": "70371035",
    "email": "mohamed.fasleemohamednawfer@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Plumber cum carpenter"
    },
    "reporting_manager": "",
    "date_of_joining": "2013-12-02",
    "employment_type": "Full-Time",
    "qid_passport_no": "27914412599",
    "id_expiry_date": "2026-11-29",
    "basic_salary": 1290.0,
    "hra": 0.0,
    "tra": 500.0,
    "other_allowances": 360.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790008736253",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-15",
    "employee_id_code": "EMP-015",
    "first_name": "Abdul",
    "last_name": "Rahmathulla parayanga Chalil",
    "gender": "Male",
    "nationality": "India",
    "date_of_birth": "1991-05-29",
    "mobile_number": "50443568",
    "email": "abdul.rahmathullaparayangachalil@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Electrician"
    },
    "reporting_manager": "",
    "date_of_joining": "2025-10-24",
    "employment_type": "Full-Time",
    "qid_passport_no": "29135625105",
    "id_expiry_date": "2026-11-04",
    "basic_salary": 1680.0,
    "hra": 0.0,
    "tra": 700.0,
    "other_allowances": 420.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790002525074",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-16",
    "employee_id_code": "EMP-016",
    "first_name": "Mohamed",
    "last_name": "Akar Faisal",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1999-06-29",
    "mobile_number": "33187366",
    "email": "mohamed.akarfaisal@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Mason cum Plumber"
    },
    "reporting_manager": "",
    "date_of_joining": "2021-11-19",
    "employment_type": "Full-Time",
    "qid_passport_no": "29914402498",
    "id_expiry_date": "2026-11-19",
    "basic_salary": 1050.0,
    "hra": 0.0,
    "tra": 450.0,
    "other_allowances": 250.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710017135771",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-17",
    "employee_id_code": "EMP-017",
    "first_name": "Laxman",
    "last_name": "Nepali",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1996-02-21",
    "mobile_number": "66898795",
    "email": "laxman.nepali@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Electrician"
    },
    "reporting_manager": "",
    "date_of_joining": "2022-01-26",
    "employment_type": "Full-Time",
    "qid_passport_no": "29652439648",
    "id_expiry_date": "2027-01-26",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 350.0,
    "other_allowances": 150.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710017762863",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-18",
    "employee_id_code": "EMP-018",
    "first_name": "Abdul",
    "last_name": "Salam Pandarathil Aliamunny",
    "gender": "Male",
    "nationality": "India",
    "date_of_birth": "1985-05-26",
    "mobile_number": "30772923",
    "email": "abdul.salampandarathilaliamunny@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Driver"
    },
    "reporting_manager": "",
    "date_of_joining": "2015-09-22",
    "employment_type": "Full-Time",
    "qid_passport_no": "28535639163",
    "id_expiry_date": "2026-09-19",
    "basic_salary": 1560.0,
    "hra": 0.0,
    "tra": 600.0,
    "other_allowances": 440.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790022518315",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-19",
    "employee_id_code": "EMP-019",
    "first_name": "Firosh",
    "last_name": "Puthanpeedikayil Kunhumon",
    "gender": "Male",
    "nationality": "India",
    "date_of_birth": "1981-02-14",
    "mobile_number": "66732539",
    "email": "firosh.puthanpeedikayilkunhumon@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Driver"
    },
    "reporting_manager": "",
    "date_of_joining": "2018-05-29",
    "employment_type": "Full-Time",
    "qid_passport_no": "28135626970",
    "id_expiry_date": "2027-05-28",
    "basic_salary": 1800.0,
    "hra": 0.0,
    "tra": 700.0,
    "other_allowances": 500.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "Provided By Company",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790036084783",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-20",
    "employee_id_code": "EMP-020",
    "first_name": "Deuman",
    "last_name": "Tamang",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1987-05-06",
    "mobile_number": "30921428",
    "email": "deuman.tamang@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Painter"
    },
    "reporting_manager": "",
    "date_of_joining": "2017-07-12",
    "employment_type": "Full-Time",
    "qid_passport_no": "28752435699",
    "id_expiry_date": "2027-07-10",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 400.0,
    "other_allowances": 250.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710011247184",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-21",
    "employee_id_code": "EMP-021",
    "first_name": "Husni",
    "last_name": "Ahamed Ashraf",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1997-11-05",
    "mobile_number": "66308998",
    "email": "husni.ahamedashraf@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2023-11-01",
    "employment_type": "Full-Time",
    "qid_passport_no": "29714408491",
    "id_expiry_date": "2026-11-01",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 400.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790037960577",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-22",
    "employee_id_code": "EMP-022",
    "first_name": "Tikaram",
    "last_name": "Chapagain",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1985-06-05",
    "mobile_number": "77669256",
    "email": "tikaram.chapagain@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2008-12-07",
    "employment_type": "Full-Time",
    "qid_passport_no": "28552422071",
    "id_expiry_date": "2026-12-04",
    "basic_salary": 1260.0,
    "hra": 0.0,
    "tra": 500.0,
    "other_allowances": 340.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790043593602",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-23",
    "employee_id_code": "EMP-023",
    "first_name": "Ram",
    "last_name": "Udgar Mandal",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1978-04-27",
    "mobile_number": "33238504",
    "email": "ram.udgarmandal@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2009-08-30",
    "employment_type": "Full-Time",
    "qid_passport_no": "27852404288",
    "id_expiry_date": "2026-08-27",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 400.0,
    "other_allowances": 250.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790040036019",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-24",
    "employee_id_code": "EMP-024",
    "first_name": "Ammar",
    "last_name": "Bahadur",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1982-05-01",
    "mobile_number": "33569791",
    "email": "ammar.bahadur@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2011-10-26",
    "employment_type": "Full-Time",
    "qid_passport_no": "28252432566",
    "id_expiry_date": "2026-10-23",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 400.0,
    "other_allowances": 250.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790022120203",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-25",
    "employee_id_code": "EMP-025",
    "first_name": "Ram",
    "last_name": "Bahdur",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1978-05-23",
    "mobile_number": "66807411",
    "email": "ram.bahdur@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2010-02-14",
    "employment_type": "Full-Time",
    "qid_passport_no": "27852420621",
    "id_expiry_date": "2027-02-11",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 400.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710017749357",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-26",
    "employee_id_code": "EMP-026",
    "first_name": "Syed",
    "last_name": "sharafullah",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1988-08-12",
    "mobile_number": "30663548",
    "email": "syed.sharafullah@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2011-05-09",
    "employment_type": "Full-Time",
    "qid_passport_no": "28814406648",
    "id_expiry_date": "2027-05-06",
    "basic_salary": 1050.0,
    "hra": 0.0,
    "tra": 400.0,
    "other_allowances": 250.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790018247713",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-27",
    "employee_id_code": "EMP-027",
    "first_name": "Mohamed",
    "last_name": "Hijlal",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1992-04-20",
    "mobile_number": "77276569",
    "email": "mohamed.hijlal@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2012-02-11",
    "employment_type": "Full-Time",
    "qid_passport_no": "29214402412",
    "id_expiry_date": "2027-02-08",
    "basic_salary": 1050.0,
    "hra": 0.0,
    "tra": 350.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790015557031",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-28",
    "employee_id_code": "EMP-028",
    "first_name": "Narayanan",
    "last_name": "Chapagain",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1996-10-02",
    "mobile_number": "30921675",
    "email": "narayanan.chapagain@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2016-01-23",
    "employment_type": "Full-Time",
    "qid_passport_no": "29652411660",
    "id_expiry_date": "2027-01-20",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 250.0,
    "other_allowances": 150.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790026199393",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-29",
    "employee_id_code": "EMP-029",
    "first_name": "Prem",
    "last_name": "Chapagain",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1994-05-15",
    "mobile_number": "33729813",
    "email": "prem.chapagain@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2016-01-23",
    "employment_type": "Full-Time",
    "qid_passport_no": "29452426707",
    "id_expiry_date": "2027-01-20",
    "basic_salary": 1100.0,
    "hra": 0.0,
    "tra": 400.0,
    "other_allowances": 250.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790006216076",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-30",
    "employee_id_code": "EMP-030",
    "first_name": "Uttamlal",
    "last_name": "Acharya",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1978-04-17",
    "mobile_number": "70552132",
    "email": "uttamlal.acharya@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2016-08-21",
    "employment_type": "Full-Time",
    "qid_passport_no": "27852430985",
    "id_expiry_date": "2026-08-18",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 300.0,
    "other_allowances": 150.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710009342724",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-31",
    "employee_id_code": "EMP-031",
    "first_name": "Padam",
    "last_name": "Bahadur BK",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1991-06-24",
    "mobile_number": "50877573",
    "email": "padam.bahadurbk@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Cleaner"
    },
    "reporting_manager": "",
    "date_of_joining": "2021-10-16",
    "employment_type": "Full-Time",
    "qid_passport_no": "29152444373",
    "id_expiry_date": "2026-10-16",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 0.0,
    "other_allowances": 300.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5104710016842237",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-32",
    "employee_id_code": "EMP-032",
    "first_name": "Mohamed",
    "last_name": "Rashath",
    "gender": "Male",
    "nationality": "Sri Lanka",
    "date_of_birth": "1980-06-15",
    "mobile_number": "77950241",
    "email": "mohamed.rashath@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2023-05-05",
    "employment_type": "Full-Time",
    "qid_passport_no": "28014417017",
    "id_expiry_date": "2027-06-09",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 0.0,
    "other_allowances": 300.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790029629560",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-33",
    "employee_id_code": "EMP-033",
    "first_name": "Raj",
    "last_name": "Kumar Budha",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1999-08-30",
    "mobile_number": "60037341",
    "email": "raj.kumarbudha@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Cleaner"
    },
    "reporting_manager": "",
    "date_of_joining": "2023-09-29",
    "employment_type": "Full-Time",
    "qid_passport_no": "29952418037",
    "id_expiry_date": "2026-09-30",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 100.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790032027992",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-34",
    "employee_id_code": "EMP-034",
    "first_name": "Tap",
    "last_name": "Bahadur BK",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1988-06-22",
    "mobile_number": "50088926",
    "email": "tap.bahadurbk@company.qa",
    "departments": {
      "name": "Maintenance"
    },
    "designations": {
      "title": "Cleaner"
    },
    "reporting_manager": "",
    "date_of_joining": "2023-09-29",
    "employment_type": "Full-Time",
    "qid_passport_no": "28852461759",
    "id_expiry_date": "2026-09-30",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 100.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790021730424",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-35",
    "employee_id_code": "EMP-035",
    "first_name": "Giriraj",
    "last_name": "Gajmer",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1982-10-26",
    "mobile_number": "30773208",
    "email": "giriraj.gajmer@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2025-01-01",
    "employment_type": "Full-Time",
    "qid_passport_no": "28252430639",
    "id_expiry_date": "2027-01-10",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 200.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790007989788",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-36",
    "employee_id_code": "EMP-036",
    "first_name": "Bakhat",
    "last_name": "Khatri",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1992-03-01",
    "mobile_number": "70240366",
    "email": "bakhat.khatri@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2025-03-21",
    "employment_type": "Full-Time",
    "qid_passport_no": "29252448446",
    "id_expiry_date": "2027-03-20",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 100.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790015733475",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-37",
    "employee_id_code": "EMP-037",
    "first_name": "Suraj",
    "last_name": "Budhathoki",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1990-10-05",
    "mobile_number": "77027824",
    "email": "suraj.budhathoki@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2025-05-05",
    "employment_type": "Full-Time",
    "qid_passport_no": "29052440333",
    "id_expiry_date": "2027-05-01",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 100.0,
    "other_allowances": 200.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790018647003",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  },
  {
    "id": "emp-seed-38",
    "employee_id_code": "EMP-038",
    "first_name": "Prakash",
    "last_name": "Ghimire",
    "gender": "Male",
    "nationality": "Nepal",
    "date_of_birth": "1982-03-10",
    "mobile_number": "77255801",
    "email": "prakash.ghimire@company.qa",
    "departments": {
      "name": "Security"
    },
    "designations": {
      "title": "Caretaker"
    },
    "reporting_manager": "",
    "date_of_joining": "2025-11-17",
    "employment_type": "Full-Time",
    "qid_passport_no": "28252449849",
    "id_expiry_date": "2026-11-17",
    "basic_salary": 1000.0,
    "hra": 0.0,
    "tra": 0.0,
    "other_allowances": 100.0,
    "benefit_telephone": "",
    "benefit_accommodation": "Provided By Company",
    "benefit_vehicle": "",
    "bank_name": "Commercial Bank",
    "iban": "CBQ5554790036988652",
    "air_ticket": "2 Years",
    "air_ticket_fare_cap": 0.0,
    "employee_status": "Active",
    "emergency_contact_name": "",
    "relation_with_employee": "",
    "emergency_contact_no": "",
    "remarks": ""
  }
];
