-- Chart of Accounts
CREATE TABLE fin_coa_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code VARCHAR(50) NOT NULL UNIQUE,
  account_name VARCHAR(255) NOT NULL,
  account_type VARCHAR(50) NOT NULL, -- Asset, Liability, Equity, Revenue, Expense
  parent_id BIGINT REFERENCES fin_coa_accounts(id),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Vouchers (Journal Entries)
CREATE TABLE fin_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_number VARCHAR(100) NOT NULL UNIQUE,
  voucher_date DATE NOT NULL,
  voucher_type VARCHAR(50) NOT NULL, -- Journal, Receipt, Payment, Contra, Sales, Purchase
  reference_no VARCHAR(100),
  description TEXT,
  total_amount NUMERIC(15, 2) NOT NULL,
  status VARCHAR(50) DEFAULT 'Draft', -- Draft, Posted, Cancelled
  posted_by VARCHAR(100),
  posted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Voucher Lines
CREATE TABLE fin_voucher_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES fin_vouchers(id) ON DELETE CASCADE,
  account_id BIGINT NOT NULL REFERENCES fin_coa_accounts(id),
  cost_center_id BIGINT, -- references fin_cost_centers
  property_id BIGINT,
  unit_id BIGINT,
  tenant_id BIGINT,
  vendor_id BIGINT,
  debit_amount NUMERIC(15, 2) DEFAULT 0,
  credit_amount NUMERIC(15, 2) DEFAULT 0,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PDC Register
CREATE TABLE fin_pdc_register (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cheque_number VARCHAR(100) NOT NULL,
  bank_id BIGINT,
  cheque_date DATE NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  tenant_id BIGINT,
  property_id BIGINT,
  unit_id BIGINT,
  status VARCHAR(50) DEFAULT 'Received', -- Received, In Hand, Deposited, Cleared, Returned
  deposit_date DATE,
  cleared_date DATE,
  returned_date DATE,
  original_pdc_id BIGINT, -- For Re-presented PDCs
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Legal Receivables
CREATE TABLE fin_legal_receivables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  property_id BIGINT,
  unit_id BIGINT,
  lease_id BIGINT,
  original_amount NUMERIC(15, 2) NOT NULL,
  outstanding_balance NUMERIC(15, 2) NOT NULL,
  escalation_date DATE NOT NULL,
  reason TEXT,
  legal_case_id VARCHAR(100),
  status VARCHAR(50) DEFAULT 'Escalated', -- Escalated, Partially Recovered, Fully Recovered, Closed, Written Off
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Deposits (Leasing 21500 and Refundable 21100)
CREATE TABLE fin_deposits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deposit_type VARCHAR(100) NOT NULL, -- Security Deposit, Qatar Cool, Kahramaa
  coa_account_code VARCHAR(50) NOT NULL, -- 21500 or 21100
  amount NUMERIC(15, 2) NOT NULL,
  tenant_id BIGINT NOT NULL,
  property_id BIGINT,
  unit_id BIGINT,
  lease_id BIGINT,
  status VARCHAR(50) DEFAULT 'Active', -- Active, Refundable, Settled, Refunded
  receipt_ref VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Payroll Sync Jobs
CREATE TABLE fin_payroll_syncs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id VARCHAR(100) NOT NULL UNIQUE,
  period VARCHAR(50) NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending', -- Pending, Validated, Posted, Failed, Duplicate
  total_amount NUMERIC(15, 2),
  error_details TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
