import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Loader2, Download, FileText, Wifi } from "lucide-react";
import { fetchFinancialReceipts, type FinancialReceipt } from "@/lib/finance/financial-receipt-service";
import { generateFinancialReceiptBlob } from "@/components/financial-receipt-template";

export const Route = createFileRoute("/cashier/receipts")({
  component: ReceiptsPage,
});

function ReceiptsPage() {
  const [financialReceipts, setFinancialReceipts] = useState<FinancialReceipt[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    void loadFinancialReceipts();
  }, []);

  async function loadFinancialReceipts() {
    setLoading(true);
    try {
      setFinancialReceipts(await fetchFinancialReceipts());
    } catch (error) {
      console.error("Failed to load generated financial receipts", error);
      setFinancialReceipts([]);
    } finally {
      setLoading(false);
    }
  }

  const handleDownload = async (receipt: FinancialReceipt) => {
    try {
      const blob = await generateFinancialReceiptBlob(receipt);
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = `Financial_Receipt_${receipt.receipt_no}.pdf`;
      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error(error);
      alert("Failed to generate financial receipt PDF.");
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold">Financial Receipts</h2>
        <p className="text-sm text-muted-foreground">
          System-generated receipts for posted financial transactions. Receipts cannot be created or edited directly from this screen.
        </p>
      </div>

      <Card>
        <CardHeader className="py-4 border-b border-border">
          <div className="flex items-center justify-between gap-4">
            <div>
              <CardTitle className="text-base font-semibold">System-Generated Financial Receipts</CardTitle>
              <CardDescription>
                One immutable receipt is generated by the database for every posted accounting event.
              </CardDescription>
            </div>
            <Badge variant="outline" className="gap-1 text-green-700 border-green-300 bg-green-50">
              <Wifi className="h-3 w-3" />
              Live Sync
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {loading ? (
            <div className="flex h-32 items-center justify-center gap-2">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Loading financial receipts...</span>
            </div>
          ) : financialReceipts.length === 0 ? (
            <div className="py-10 text-center">
              <FileText className="mx-auto mb-3 h-8 w-8 text-muted-foreground" />
              <p className="text-sm text-muted-foreground">No system-generated financial receipts found.</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-muted/10 text-left text-xs text-muted-foreground">
                  <tr>
                    <th className="px-4 py-3 font-medium">Receipt No.</th>
                    <th className="px-4 py-3 font-medium">Category</th>
                    <th className="px-4 py-3 font-medium">Direction</th>
                    <th className="px-4 py-3 font-medium">Date</th>
                    <th className="px-4 py-3 font-medium">Reference</th>
                    <th className="px-4 py-3 font-medium">Payment Method</th>
                    <th className="px-4 py-3 font-medium text-right">Amount</th>
                    <th className="px-4 py-3 font-medium text-right">Status</th>
                    <th className="px-4 py-3 font-medium text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {financialReceipts.map((receipt) => (
                    <tr key={receipt.id} className="hover:bg-muted/10">
                      <td className="px-4 py-3 font-mono text-xs font-semibold">{receipt.receipt_no}</td>
                      <td className="px-4 py-3 text-xs">{receipt.receipt_category}</td>
                      <td className="px-4 py-3 text-xs">{receipt.direction}</td>
                      <td className="px-4 py-3 text-xs text-muted-foreground">{receipt.receipt_date}</td>
                      <td className="px-4 py-3 text-xs text-muted-foreground">
                        {receipt.reference_no || receipt.instrument_reference || "-"}
                      </td>
                      <td className="px-4 py-3 text-xs">{receipt.payment_method || "-"}</td>
                      <td className="px-4 py-3 text-right font-semibold">
                        {receipt.currency_code} {Number(receipt.amount).toLocaleString()}
                      </td>
                      <td className="px-4 py-3 text-right">
                        <Badge variant="outline" className="text-green-700 border-green-300 bg-green-50 text-xs">
                          {receipt.status}
                        </Badge>
                      </td>
                      <td className="px-4 py-3 text-right">
                        <Button variant="outline" size="sm" className="gap-1" onClick={() => void handleDownload(receipt)}>
                          <Download className="h-3.5 w-3.5" />
                          PDF
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
