import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAppData } from "@/lib/app-data-context";
import { ArrowDownLeft, ArrowUpRight, Receipt, Banknote, RotateCcw, Plus } from "lucide-react";

export const Route = createFileRoute("/prop-mgr/finance/transactions")({
  component: TransactionsPage,
});

const VOUCHER_TYPES = [
  { value: "Receipt", label: "Receipt Voucher", icon: ArrowDownLeft, color: "text-green-600 bg-green-50" },
  { value: "Deposit", label: "Deposit Voucher", icon: Banknote, color: "text-blue-600 bg-blue-50" },
  { value: "Cheque Return", label: "Cheque Returned", icon: RotateCcw, color: "text-red-600 bg-red-50" },
  { value: "Rent Income", label: "Rent Income", icon: Receipt, color: "text-emerald-600 bg-emerald-50" },
  { value: "Payment", label: "Payment Voucher", icon: ArrowUpRight, color: "text-orange-600 bg-orange-50" },
];

function toVoucherType(name: string) {
  if (name.includes("Deposit")) return "Deposit";
  if (name.includes("Cheque Return")) return "Cheque Return";
  if (name.includes("Rent Income") || name.includes("Rental Income")) return "Rent Income";
  if (name.includes("Payment")) return "Payment";
  return "Receipt";
}

function TransactionsPage() {
  const { vouchers } = useAppData();
  const [activeType, setActiveType] = useState("all");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const normalized = vouchers.map((voucher) => ({
    id: voucher.id,
    voucher_no: voucher.receiptNo ?? voucher.id,
    voucher_type: toVoucherType(voucher.name),
    amount: voucher.amount,
    notes: `${voucher.name}${voucher.period ? ` | ${voucher.period}` : ""}`,
    entries: [
      { id: `${voucher.id}-dr`, account_name: voucher.debit, debit: voucher.amount, credit: 0 },
      { id: `${voucher.id}-cr`, account_name: voucher.credit, debit: 0, credit: voucher.amount },
    ],
  }));

  const filtered = activeType === "all" ? normalized : normalized.filter((voucher) => voucher.voucher_type === activeType);
  const totalDr = filtered.reduce((sum, voucher) => sum + voucher.entries.reduce((acc, entry) => acc + entry.debit, 0), 0);
  const totalCr = filtered.reduce((sum, voucher) => sum + voucher.entries.reduce((acc, entry) => acc + entry.credit, 0), 0);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Finance Transactions</h2>
          <p className="text-sm text-muted-foreground">Shared vouchers generated by leasing, cashier, and finance flows.</p>
        </div>
        <Button disabled>
          <Plus className="h-4 w-4 mr-2" />
          New Voucher
        </Button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        {VOUCHER_TYPES.map((voucherType) => {
          const count = normalized.filter((voucher) => voucher.voucher_type === voucherType.value).length;
          const total = normalized.filter((voucher) => voucher.voucher_type === voucherType.value).reduce((sum, voucher) => sum + voucher.amount, 0);
          return (
            <Card
              key={voucherType.value}
              className={`cursor-pointer transition-all border-2 ${activeType === voucherType.value ? "border-primary" : "border-border hover:border-primary/30"}`}
              onClick={() => setActiveType(activeType === voucherType.value ? "all" : voucherType.value)}
            >
              <CardContent className="p-4">
                <div className={`inline-flex items-center justify-center rounded-lg p-2 mb-2 ${voucherType.color}`}>
                  <voucherType.icon className="h-4 w-4" />
                </div>
                <div className="text-xs font-medium text-muted-foreground">{voucherType.label}</div>
                <div className="text-lg font-bold mt-1">{count}</div>
                <div className="text-xs text-muted-foreground">QR {total.toLocaleString()}</div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="flex gap-6 px-4 py-3 bg-muted/30 rounded-xl border border-border text-sm">
        <div className="flex items-center gap-2">
          <span className="text-muted-foreground">Total Dr:</span>
          <span className="font-semibold text-blue-600">QR {totalDr.toLocaleString()}</span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-muted-foreground">Total Cr:</span>
          <span className="font-semibold text-red-600">QR {totalCr.toLocaleString()}</span>
        </div>
        <div className="ml-auto text-muted-foreground">{filtered.length} vouchers shown</div>
      </div>

      <Card>
        <CardContent className="p-0">
          {filtered.length === 0 ? (
            <div className="py-12 text-center text-muted-foreground">No transactions found</div>
          ) : (
            <div className="divide-y divide-border">
              {filtered.map((voucher) => {
                const info = VOUCHER_TYPES.find((item) => item.value === voucher.voucher_type) || VOUCHER_TYPES[0];
                const isExpanded = expandedId === voucher.id;
                return (
                  <div key={voucher.id}>
                    <div className="flex items-center gap-4 px-5 py-4 hover:bg-muted/10 cursor-pointer transition-colors" onClick={() => setExpandedId(isExpanded ? null : voucher.id)}>
                      <div className={`flex items-center justify-center rounded-lg h-9 w-9 flex-shrink-0 ${info.color}`}>
                        <info.icon className="h-4 w-4" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="font-semibold text-sm">{voucher.voucher_no}</div>
                        <div className="text-xs text-muted-foreground">{info.label}</div>
                        <div className="text-xs text-muted-foreground mt-0.5 truncate">{voucher.notes}</div>
                      </div>
                      <div className="text-right flex-shrink-0">
                        <div className="font-semibold text-sm">QR {voucher.amount.toLocaleString()}</div>
                        <div className="text-xs text-muted-foreground">{voucher.entries.length} lines</div>
                      </div>
                    </div>
                    {isExpanded && (
                      <div className="bg-muted/5 border-t border-border">
                        <table className="w-full text-sm">
                          <thead>
                            <tr className="border-b border-border">
                              <th className="px-10 py-2 text-left text-xs text-muted-foreground font-medium">Account Name</th>
                              <th className="px-6 py-2 text-right text-xs text-muted-foreground font-medium">Debit (QR)</th>
                              <th className="px-6 py-2 text-right text-xs text-muted-foreground font-medium">Credit (QR)</th>
                            </tr>
                          </thead>
                          <tbody>
                            {voucher.entries.map((entry) => (
                              <tr key={entry.id} className="border-b border-border/50 last:border-0">
                                <td className="px-10 py-2 text-sm">{entry.account_name}</td>
                                <td className="px-6 py-2 text-right font-mono text-sm text-blue-600">{entry.debit > 0 ? entry.debit.toLocaleString() : "-"}</td>
                                <td className="px-6 py-2 text-right font-mono text-sm text-red-600">{entry.credit > 0 ? entry.credit.toLocaleString() : "-"}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
