/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PropMgrRouteImport } from './routes/prop-mgr'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LeasingRouteImport } from './routes/leasing'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as PropMgrIndexRouteImport } from './routes/prop-mgr.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance.index'
import { Route as LeasingIndexRouteImport } from './routes/leasing.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as CashierIndexRouteImport } from './routes/cashier.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminTenantsRouteImport } from './routes/super-admin.tenants'
import { Route as SuperAdminSecurityRouteImport } from './routes/super-admin.security'
import { Route as SuperAdminPermissionsRouteImport } from './routes/super-admin.permissions'
import { Route as SuperAdminNotificationsRouteImport } from './routes/super-admin.notifications'
import { Route as SuperAdminConfigRouteImport } from './routes/super-admin.config'
import { Route as SuperAdminBillingRouteImport } from './routes/super-admin.billing'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as SalesReservationsRouteImport } from './routes/sales.reservations'
import { Route as SalesListingsRouteImport } from './routes/sales.listings'
import { Route as SalesContractsRouteImport } from './routes/sales.contracts'
import { Route as SalesAppointmentsRouteImport } from './routes/sales.appointments'
import { Route as PropMgrUsersRouteImport } from './routes/prop-mgr.users'
import { Route as PropMgrUnitsRouteImport } from './routes/prop-mgr.units'
import { Route as PropMgrPropertiesRouteImport } from './routes/prop-mgr.properties'
import { Route as PropMgrMaintenanceRouteImport } from './routes/prop-mgr.maintenance'
import { Route as PropMgrLeasingRouteImport } from './routes/prop-mgr.leasing'
import { Route as PropMgrLeasesRouteImport } from './routes/prop-mgr.leases'
import { Route as PropMgrFinanceRouteImport } from './routes/prop-mgr.finance'
import { Route as PropMgrCreateRouteImport } from './routes/prop-mgr.create'
import { Route as PropMgrAssetsRouteImport } from './routes/prop-mgr.assets'
import { Route as PropMgrApprovalsRouteImport } from './routes/prop-mgr.approvals'
import { Route as PortalTicketsRouteImport } from './routes/portal.tickets'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalCommunityRouteImport } from './routes/portal.community'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'
import { Route as OwnerStatementsRouteImport } from './routes/owner.statements'
import { Route as OwnerPropertiesRouteImport } from './routes/owner.properties'
import { Route as OwnerDistributionsRouteImport } from './routes/owner.distributions'
import { Route as OwnerApprovalsRouteImport } from './routes/owner.approvals'
import { Route as MaintenanceTicketsRouteImport } from './routes/maintenance.tickets'
import { Route as MaintenanceInventoryRouteImport } from './routes/maintenance.inventory'
import { Route as LeasingManageRouteImport } from './routes/leasing.manage'
import { Route as LeasingCreateRouteImport } from './routes/leasing.create'
import { Route as FinanceReceivablesRouteImport } from './routes/finance.receivables'
import { Route as FinanceLedgerRouteImport } from './routes/finance.ledger'
import { Route as FinanceJournalRouteImport } from './routes/finance.journal'
import { Route as CashierReceiptsRouteImport } from './routes/cashier.receipts'
import { Route as CashierPdcRouteImport } from './routes/cashier.pdc'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUnitsRouteImport } from './routes/admin.units'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminMastersRouteImport } from './routes/admin.masters'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminLeasesRouteImport } from './routes/admin.leases'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin.finance.index'
import { Route as PropMgrUnitsPricingRouteImport } from './routes/prop-mgr.units.pricing'
import { Route as PropMgrManageIdRouteImport } from './routes/prop-mgr.manage.$id'
import { Route as PropMgrFinanceTransactionsRouteImport } from './routes/prop-mgr.finance.transactions'
import { Route as PortalCommunityReviewsRouteImport } from './routes/portal.community.reviews'
import { Route as PortalCommunityEventsRouteImport } from './routes/portal.community.events'
import { Route as AdminLeasesNewRouteImport } from './routes/admin.leases.new'
import { Route as AdminFinanceReceiptsRouteImport } from './routes/admin.finance.receipts'
import { Route as AdminFinancePayablesRouteImport } from './routes/admin.finance.payables'
import { Route as AdminFinanceLedgerRouteImport } from './routes/admin.finance.ledger'
import { Route as AdminFinanceCoaRouteImport } from './routes/admin.finance.coa'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PropMgrRoute = PropMgrRouteImport.update({
  id: '/prop-mgr',
  path: '/prop-mgr',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasingRoute = LeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const PropMgrIndexRoute = PropMgrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropMgrRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaintenanceRoute,
} as any)
const LeasingIndexRoute = LeasingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeasingRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const CashierIndexRoute = CashierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTenantsRoute = SuperAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSecurityRoute = SuperAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPermissionsRoute = SuperAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminNotificationsRoute = SuperAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminConfigRoute = SuperAdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBillingRoute = SuperAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SalesReservationsRoute = SalesReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => SalesRoute,
} as any)
const SalesListingsRoute = SalesListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => SalesRoute,
} as any)
const SalesContractsRoute = SalesContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => SalesRoute,
} as any)
const SalesAppointmentsRoute = SalesAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => SalesRoute,
} as any)
const PropMgrUsersRoute = PropMgrUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrUnitsRoute = PropMgrUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrPropertiesRoute = PropMgrPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrMaintenanceRoute = PropMgrMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrLeasingRoute = PropMgrLeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrLeasesRoute = PropMgrLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrFinanceRoute = PropMgrFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrCreateRoute = PropMgrCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrAssetsRoute = PropMgrAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrApprovalsRoute = PropMgrApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => PropMgrRoute,
} as any)
const PortalTicketsRoute = PortalTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCommunityRoute = PortalCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const OwnerStatementsRoute = OwnerStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDistributionsRoute = OwnerDistributionsRouteImport.update({
  id: '/distributions',
  path: '/distributions',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerApprovalsRoute = OwnerApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => OwnerRoute,
} as any)
const MaintenanceTicketsRoute = MaintenanceTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceInventoryRoute = MaintenanceInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MaintenanceRoute,
} as any)
const LeasingManageRoute = LeasingManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => LeasingRoute,
} as any)
const LeasingCreateRoute = LeasingCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LeasingRoute,
} as any)
const FinanceReceivablesRoute = FinanceReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceLedgerRoute = FinanceLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceJournalRoute = FinanceJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => FinanceRoute,
} as any)
const CashierReceiptsRoute = CashierReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => CashierRoute,
} as any)
const CashierPdcRoute = CashierPdcRouteImport.update({
  id: '/pdc',
  path: '/pdc',
  getParentRoute: () => CashierRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitsRoute = AdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMastersRoute = AdminMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeasesRoute = AdminLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const PropMgrUnitsPricingRoute = PropMgrUnitsPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PropMgrUnitsRoute,
} as any)
const PropMgrManageIdRoute = PropMgrManageIdRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => PropMgrRoute,
} as any)
const PropMgrFinanceTransactionsRoute =
  PropMgrFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => PropMgrFinanceRoute,
  } as any)
const PortalCommunityReviewsRoute = PortalCommunityReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => PortalCommunityRoute,
} as any)
const PortalCommunityEventsRoute = PortalCommunityEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalCommunityRoute,
} as any)
const AdminLeasesNewRoute = AdminLeasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLeasesRoute,
} as any)
const AdminFinanceReceiptsRoute = AdminFinanceReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinancePayablesRoute = AdminFinancePayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceLedgerRoute = AdminFinanceLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceCoaRoute = AdminFinanceCoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => AdminFinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/guest': typeof GuestRoute
  '/leasing': typeof LeasingRouteWithChildren
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/prop-mgr': typeof PropMgrRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/leases': typeof AdminLeasesRouteWithChildren
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cashier/pdc': typeof CashierPdcRoute
  '/cashier/receipts': typeof CashierReceiptsRoute
  '/finance/journal': typeof FinanceJournalRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/receivables': typeof FinanceReceivablesRoute
  '/leasing/create': typeof LeasingCreateRoute
  '/leasing/manage': typeof LeasingManageRoute
  '/maintenance/inventory': typeof MaintenanceInventoryRoute
  '/maintenance/tickets': typeof MaintenanceTicketsRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/owner/distributions': typeof OwnerDistributionsRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/community': typeof PortalCommunityRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/prop-mgr/approvals': typeof PropMgrApprovalsRoute
  '/prop-mgr/assets': typeof PropMgrAssetsRoute
  '/prop-mgr/create': typeof PropMgrCreateRoute
  '/prop-mgr/finance': typeof PropMgrFinanceRouteWithChildren
  '/prop-mgr/leases': typeof PropMgrLeasesRoute
  '/prop-mgr/leasing': typeof PropMgrLeasingRoute
  '/prop-mgr/maintenance': typeof PropMgrMaintenanceRoute
  '/prop-mgr/properties': typeof PropMgrPropertiesRoute
  '/prop-mgr/units': typeof PropMgrUnitsRouteWithChildren
  '/prop-mgr/users': typeof PropMgrUsersRoute
  '/sales/appointments': typeof SalesAppointmentsRoute
  '/sales/contracts': typeof SalesContractsRoute
  '/sales/listings': typeof SalesListingsRoute
  '/sales/reservations': typeof SalesReservationsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/config': typeof SuperAdminConfigRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/permissions': typeof SuperAdminPermissionsRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/cashier/': typeof CashierIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/leasing/': typeof LeasingIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/prop-mgr/': typeof PropMgrIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/finance/coa': typeof AdminFinanceCoaRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/finance/payables': typeof AdminFinancePayablesRoute
  '/admin/finance/receipts': typeof AdminFinanceReceiptsRoute
  '/admin/leases/new': typeof AdminLeasesNewRoute
  '/portal/community/events': typeof PortalCommunityEventsRoute
  '/portal/community/reviews': typeof PortalCommunityReviewsRoute
  '/prop-mgr/finance/transactions': typeof PropMgrFinanceTransactionsRoute
  '/prop-mgr/manage/$id': typeof PropMgrManageIdRoute
  '/prop-mgr/units/pricing': typeof PropMgrUnitsPricingRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guest': typeof GuestRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leases': typeof AdminLeasesRouteWithChildren
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cashier/pdc': typeof CashierPdcRoute
  '/cashier/receipts': typeof CashierReceiptsRoute
  '/finance/journal': typeof FinanceJournalRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/receivables': typeof FinanceReceivablesRoute
  '/leasing/create': typeof LeasingCreateRoute
  '/leasing/manage': typeof LeasingManageRoute
  '/maintenance/inventory': typeof MaintenanceInventoryRoute
  '/maintenance/tickets': typeof MaintenanceTicketsRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/owner/distributions': typeof OwnerDistributionsRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/community': typeof PortalCommunityRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/prop-mgr/approvals': typeof PropMgrApprovalsRoute
  '/prop-mgr/assets': typeof PropMgrAssetsRoute
  '/prop-mgr/create': typeof PropMgrCreateRoute
  '/prop-mgr/finance': typeof PropMgrFinanceRouteWithChildren
  '/prop-mgr/leases': typeof PropMgrLeasesRoute
  '/prop-mgr/leasing': typeof PropMgrLeasingRoute
  '/prop-mgr/maintenance': typeof PropMgrMaintenanceRoute
  '/prop-mgr/properties': typeof PropMgrPropertiesRoute
  '/prop-mgr/units': typeof PropMgrUnitsRouteWithChildren
  '/prop-mgr/users': typeof PropMgrUsersRoute
  '/sales/appointments': typeof SalesAppointmentsRoute
  '/sales/contracts': typeof SalesContractsRoute
  '/sales/listings': typeof SalesListingsRoute
  '/sales/reservations': typeof SalesReservationsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/config': typeof SuperAdminConfigRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/permissions': typeof SuperAdminPermissionsRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/cashier': typeof CashierIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/leasing': typeof LeasingIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/portal': typeof PortalIndexRoute
  '/prop-mgr': typeof PropMgrIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/admin/finance/coa': typeof AdminFinanceCoaRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/finance/payables': typeof AdminFinancePayablesRoute
  '/admin/finance/receipts': typeof AdminFinanceReceiptsRoute
  '/admin/leases/new': typeof AdminLeasesNewRoute
  '/portal/community/events': typeof PortalCommunityEventsRoute
  '/portal/community/reviews': typeof PortalCommunityReviewsRoute
  '/prop-mgr/finance/transactions': typeof PropMgrFinanceTransactionsRoute
  '/prop-mgr/manage/$id': typeof PropMgrManageIdRoute
  '/prop-mgr/units/pricing': typeof PropMgrUnitsPricingRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cashier': typeof CashierRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/guest': typeof GuestRoute
  '/leasing': typeof LeasingRouteWithChildren
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/prop-mgr': typeof PropMgrRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/leases': typeof AdminLeasesRouteWithChildren
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cashier/pdc': typeof CashierPdcRoute
  '/cashier/receipts': typeof CashierReceiptsRoute
  '/finance/journal': typeof FinanceJournalRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/receivables': typeof FinanceReceivablesRoute
  '/leasing/create': typeof LeasingCreateRoute
  '/leasing/manage': typeof LeasingManageRoute
  '/maintenance/inventory': typeof MaintenanceInventoryRoute
  '/maintenance/tickets': typeof MaintenanceTicketsRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/owner/distributions': typeof OwnerDistributionsRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/community': typeof PortalCommunityRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/prop-mgr/approvals': typeof PropMgrApprovalsRoute
  '/prop-mgr/assets': typeof PropMgrAssetsRoute
  '/prop-mgr/create': typeof PropMgrCreateRoute
  '/prop-mgr/finance': typeof PropMgrFinanceRouteWithChildren
  '/prop-mgr/leases': typeof PropMgrLeasesRoute
  '/prop-mgr/leasing': typeof PropMgrLeasingRoute
  '/prop-mgr/maintenance': typeof PropMgrMaintenanceRoute
  '/prop-mgr/properties': typeof PropMgrPropertiesRoute
  '/prop-mgr/units': typeof PropMgrUnitsRouteWithChildren
  '/prop-mgr/users': typeof PropMgrUsersRoute
  '/sales/appointments': typeof SalesAppointmentsRoute
  '/sales/contracts': typeof SalesContractsRoute
  '/sales/listings': typeof SalesListingsRoute
  '/sales/reservations': typeof SalesReservationsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/config': typeof SuperAdminConfigRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/permissions': typeof SuperAdminPermissionsRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/cashier/': typeof CashierIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/leasing/': typeof LeasingIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/prop-mgr/': typeof PropMgrIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/finance/coa': typeof AdminFinanceCoaRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/finance/payables': typeof AdminFinancePayablesRoute
  '/admin/finance/receipts': typeof AdminFinanceReceiptsRoute
  '/admin/leases/new': typeof AdminLeasesNewRoute
  '/portal/community/events': typeof PortalCommunityEventsRoute
  '/portal/community/reviews': typeof PortalCommunityReviewsRoute
  '/prop-mgr/finance/transactions': typeof PropMgrFinanceTransactionsRoute
  '/prop-mgr/manage/$id': typeof PropMgrManageIdRoute
  '/prop-mgr/units/pricing': typeof PropMgrUnitsPricingRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cashier'
    | '/finance'
    | '/guest'
    | '/leasing'
    | '/maintenance'
    | '/owner'
    | '/portal'
    | '/prop-mgr'
    | '/sales'
    | '/sitemap.xml'
    | '/super-admin'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/leases'
    | '/admin/maintenance'
    | '/admin/masters'
    | '/admin/permissions'
    | '/admin/properties'
    | '/admin/units'
    | '/admin/users'
    | '/cashier/pdc'
    | '/cashier/receipts'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/receivables'
    | '/leasing/create'
    | '/leasing/manage'
    | '/maintenance/inventory'
    | '/maintenance/tickets'
    | '/owner/approvals'
    | '/owner/distributions'
    | '/owner/properties'
    | '/owner/statements'
    | '/portal/bookings'
    | '/portal/community'
    | '/portal/documents'
    | '/portal/payments'
    | '/portal/settings'
    | '/portal/tickets'
    | '/prop-mgr/approvals'
    | '/prop-mgr/assets'
    | '/prop-mgr/create'
    | '/prop-mgr/finance'
    | '/prop-mgr/leases'
    | '/prop-mgr/leasing'
    | '/prop-mgr/maintenance'
    | '/prop-mgr/properties'
    | '/prop-mgr/units'
    | '/prop-mgr/users'
    | '/sales/appointments'
    | '/sales/contracts'
    | '/sales/listings'
    | '/sales/reservations'
    | '/super-admin/analytics'
    | '/super-admin/billing'
    | '/super-admin/config'
    | '/super-admin/notifications'
    | '/super-admin/permissions'
    | '/super-admin/security'
    | '/super-admin/tenants'
    | '/super-admin/users'
    | '/admin/'
    | '/cashier/'
    | '/finance/'
    | '/leasing/'
    | '/maintenance/'
    | '/portal/'
    | '/prop-mgr/'
    | '/super-admin/'
    | '/admin/finance/coa'
    | '/admin/finance/ledger'
    | '/admin/finance/payables'
    | '/admin/finance/receipts'
    | '/admin/leases/new'
    | '/portal/community/events'
    | '/portal/community/reviews'
    | '/prop-mgr/finance/transactions'
    | '/prop-mgr/manage/$id'
    | '/prop-mgr/units/pricing'
    | '/admin/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guest'
    | '/owner'
    | '/sales'
    | '/sitemap.xml'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/leases'
    | '/admin/maintenance'
    | '/admin/masters'
    | '/admin/permissions'
    | '/admin/properties'
    | '/admin/units'
    | '/admin/users'
    | '/cashier/pdc'
    | '/cashier/receipts'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/receivables'
    | '/leasing/create'
    | '/leasing/manage'
    | '/maintenance/inventory'
    | '/maintenance/tickets'
    | '/owner/approvals'
    | '/owner/distributions'
    | '/owner/properties'
    | '/owner/statements'
    | '/portal/bookings'
    | '/portal/community'
    | '/portal/documents'
    | '/portal/payments'
    | '/portal/settings'
    | '/portal/tickets'
    | '/prop-mgr/approvals'
    | '/prop-mgr/assets'
    | '/prop-mgr/create'
    | '/prop-mgr/finance'
    | '/prop-mgr/leases'
    | '/prop-mgr/leasing'
    | '/prop-mgr/maintenance'
    | '/prop-mgr/properties'
    | '/prop-mgr/units'
    | '/prop-mgr/users'
    | '/sales/appointments'
    | '/sales/contracts'
    | '/sales/listings'
    | '/sales/reservations'
    | '/super-admin/analytics'
    | '/super-admin/billing'
    | '/super-admin/config'
    | '/super-admin/notifications'
    | '/super-admin/permissions'
    | '/super-admin/security'
    | '/super-admin/tenants'
    | '/super-admin/users'
    | '/admin'
    | '/cashier'
    | '/finance'
    | '/leasing'
    | '/maintenance'
    | '/portal'
    | '/prop-mgr'
    | '/super-admin'
    | '/admin/finance/coa'
    | '/admin/finance/ledger'
    | '/admin/finance/payables'
    | '/admin/finance/receipts'
    | '/admin/leases/new'
    | '/portal/community/events'
    | '/portal/community/reviews'
    | '/prop-mgr/finance/transactions'
    | '/prop-mgr/manage/$id'
    | '/prop-mgr/units/pricing'
    | '/admin/finance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cashier'
    | '/finance'
    | '/guest'
    | '/leasing'
    | '/maintenance'
    | '/owner'
    | '/portal'
    | '/prop-mgr'
    | '/sales'
    | '/sitemap.xml'
    | '/super-admin'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/leases'
    | '/admin/maintenance'
    | '/admin/masters'
    | '/admin/permissions'
    | '/admin/properties'
    | '/admin/units'
    | '/admin/users'
    | '/cashier/pdc'
    | '/cashier/receipts'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/receivables'
    | '/leasing/create'
    | '/leasing/manage'
    | '/maintenance/inventory'
    | '/maintenance/tickets'
    | '/owner/approvals'
    | '/owner/distributions'
    | '/owner/properties'
    | '/owner/statements'
    | '/portal/bookings'
    | '/portal/community'
    | '/portal/documents'
    | '/portal/payments'
    | '/portal/settings'
    | '/portal/tickets'
    | '/prop-mgr/approvals'
    | '/prop-mgr/assets'
    | '/prop-mgr/create'
    | '/prop-mgr/finance'
    | '/prop-mgr/leases'
    | '/prop-mgr/leasing'
    | '/prop-mgr/maintenance'
    | '/prop-mgr/properties'
    | '/prop-mgr/units'
    | '/prop-mgr/users'
    | '/sales/appointments'
    | '/sales/contracts'
    | '/sales/listings'
    | '/sales/reservations'
    | '/super-admin/analytics'
    | '/super-admin/billing'
    | '/super-admin/config'
    | '/super-admin/notifications'
    | '/super-admin/permissions'
    | '/super-admin/security'
    | '/super-admin/tenants'
    | '/super-admin/users'
    | '/admin/'
    | '/cashier/'
    | '/finance/'
    | '/leasing/'
    | '/maintenance/'
    | '/portal/'
    | '/prop-mgr/'
    | '/super-admin/'
    | '/admin/finance/coa'
    | '/admin/finance/ledger'
    | '/admin/finance/payables'
    | '/admin/finance/receipts'
    | '/admin/leases/new'
    | '/portal/community/events'
    | '/portal/community/reviews'
    | '/prop-mgr/finance/transactions'
    | '/prop-mgr/manage/$id'
    | '/prop-mgr/units/pricing'
    | '/admin/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CashierRoute: typeof CashierRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  GuestRoute: typeof GuestRoute
  LeasingRoute: typeof LeasingRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PropMgrRoute: typeof PropMgrRouteWithChildren
  SalesRoute: typeof SalesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prop-mgr': {
      id: '/prop-mgr'
      path: '/prop-mgr'
      fullPath: '/prop-mgr'
      preLoaderRoute: typeof PropMgrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leasing': {
      id: '/leasing'
      path: '/leasing'
      fullPath: '/leasing'
      preLoaderRoute: typeof LeasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/prop-mgr/': {
      id: '/prop-mgr/'
      path: '/'
      fullPath: '/prop-mgr/'
      preLoaderRoute: typeof PropMgrIndexRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/leasing/': {
      id: '/leasing/'
      path: '/'
      fullPath: '/leasing/'
      preLoaderRoute: typeof LeasingIndexRouteImport
      parentRoute: typeof LeasingRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/cashier/': {
      id: '/cashier/'
      path: '/'
      fullPath: '/cashier/'
      preLoaderRoute: typeof CashierIndexRouteImport
      parentRoute: typeof CashierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/tenants': {
      id: '/super-admin/tenants'
      path: '/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof SuperAdminTenantsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/security': {
      id: '/super-admin/security'
      path: '/security'
      fullPath: '/super-admin/security'
      preLoaderRoute: typeof SuperAdminSecurityRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/permissions': {
      id: '/super-admin/permissions'
      path: '/permissions'
      fullPath: '/super-admin/permissions'
      preLoaderRoute: typeof SuperAdminPermissionsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/notifications': {
      id: '/super-admin/notifications'
      path: '/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof SuperAdminNotificationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/config': {
      id: '/super-admin/config'
      path: '/config'
      fullPath: '/super-admin/config'
      preLoaderRoute: typeof SuperAdminConfigRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/billing': {
      id: '/super-admin/billing'
      path: '/billing'
      fullPath: '/super-admin/billing'
      preLoaderRoute: typeof SuperAdminBillingRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/sales/reservations': {
      id: '/sales/reservations'
      path: '/reservations'
      fullPath: '/sales/reservations'
      preLoaderRoute: typeof SalesReservationsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/listings': {
      id: '/sales/listings'
      path: '/listings'
      fullPath: '/sales/listings'
      preLoaderRoute: typeof SalesListingsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/contracts': {
      id: '/sales/contracts'
      path: '/contracts'
      fullPath: '/sales/contracts'
      preLoaderRoute: typeof SalesContractsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/appointments': {
      id: '/sales/appointments'
      path: '/appointments'
      fullPath: '/sales/appointments'
      preLoaderRoute: typeof SalesAppointmentsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/prop-mgr/users': {
      id: '/prop-mgr/users'
      path: '/users'
      fullPath: '/prop-mgr/users'
      preLoaderRoute: typeof PropMgrUsersRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/units': {
      id: '/prop-mgr/units'
      path: '/units'
      fullPath: '/prop-mgr/units'
      preLoaderRoute: typeof PropMgrUnitsRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/properties': {
      id: '/prop-mgr/properties'
      path: '/properties'
      fullPath: '/prop-mgr/properties'
      preLoaderRoute: typeof PropMgrPropertiesRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/maintenance': {
      id: '/prop-mgr/maintenance'
      path: '/maintenance'
      fullPath: '/prop-mgr/maintenance'
      preLoaderRoute: typeof PropMgrMaintenanceRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/leasing': {
      id: '/prop-mgr/leasing'
      path: '/leasing'
      fullPath: '/prop-mgr/leasing'
      preLoaderRoute: typeof PropMgrLeasingRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/leases': {
      id: '/prop-mgr/leases'
      path: '/leases'
      fullPath: '/prop-mgr/leases'
      preLoaderRoute: typeof PropMgrLeasesRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/finance': {
      id: '/prop-mgr/finance'
      path: '/finance'
      fullPath: '/prop-mgr/finance'
      preLoaderRoute: typeof PropMgrFinanceRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/create': {
      id: '/prop-mgr/create'
      path: '/create'
      fullPath: '/prop-mgr/create'
      preLoaderRoute: typeof PropMgrCreateRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/assets': {
      id: '/prop-mgr/assets'
      path: '/assets'
      fullPath: '/prop-mgr/assets'
      preLoaderRoute: typeof PropMgrAssetsRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/approvals': {
      id: '/prop-mgr/approvals'
      path: '/approvals'
      fullPath: '/prop-mgr/approvals'
      preLoaderRoute: typeof PropMgrApprovalsRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/portal/tickets': {
      id: '/portal/tickets'
      path: '/tickets'
      fullPath: '/portal/tickets'
      preLoaderRoute: typeof PortalTicketsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/community': {
      id: '/portal/community'
      path: '/community'
      fullPath: '/portal/community'
      preLoaderRoute: typeof PortalCommunityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/owner/statements': {
      id: '/owner/statements'
      path: '/statements'
      fullPath: '/owner/statements'
      preLoaderRoute: typeof OwnerStatementsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/distributions': {
      id: '/owner/distributions'
      path: '/distributions'
      fullPath: '/owner/distributions'
      preLoaderRoute: typeof OwnerDistributionsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/approvals': {
      id: '/owner/approvals'
      path: '/approvals'
      fullPath: '/owner/approvals'
      preLoaderRoute: typeof OwnerApprovalsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/maintenance/tickets': {
      id: '/maintenance/tickets'
      path: '/tickets'
      fullPath: '/maintenance/tickets'
      preLoaderRoute: typeof MaintenanceTicketsRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/inventory': {
      id: '/maintenance/inventory'
      path: '/inventory'
      fullPath: '/maintenance/inventory'
      preLoaderRoute: typeof MaintenanceInventoryRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/leasing/manage': {
      id: '/leasing/manage'
      path: '/manage'
      fullPath: '/leasing/manage'
      preLoaderRoute: typeof LeasingManageRouteImport
      parentRoute: typeof LeasingRoute
    }
    '/leasing/create': {
      id: '/leasing/create'
      path: '/create'
      fullPath: '/leasing/create'
      preLoaderRoute: typeof LeasingCreateRouteImport
      parentRoute: typeof LeasingRoute
    }
    '/finance/receivables': {
      id: '/finance/receivables'
      path: '/receivables'
      fullPath: '/finance/receivables'
      preLoaderRoute: typeof FinanceReceivablesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/ledger': {
      id: '/finance/ledger'
      path: '/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof FinanceLedgerRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/journal': {
      id: '/finance/journal'
      path: '/journal'
      fullPath: '/finance/journal'
      preLoaderRoute: typeof FinanceJournalRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/cashier/receipts': {
      id: '/cashier/receipts'
      path: '/receipts'
      fullPath: '/cashier/receipts'
      preLoaderRoute: typeof CashierReceiptsRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/pdc': {
      id: '/cashier/pdc'
      path: '/pdc'
      fullPath: '/cashier/pdc'
      preLoaderRoute: typeof CashierPdcRouteImport
      parentRoute: typeof CashierRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/units': {
      id: '/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AdminUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/masters': {
      id: '/admin/masters'
      path: '/masters'
      fullPath: '/admin/masters'
      preLoaderRoute: typeof AdminMastersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leases': {
      id: '/admin/leases'
      path: '/leases'
      fullPath: '/admin/leases'
      preLoaderRoute: typeof AdminLeasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/prop-mgr/units/pricing': {
      id: '/prop-mgr/units/pricing'
      path: '/pricing'
      fullPath: '/prop-mgr/units/pricing'
      preLoaderRoute: typeof PropMgrUnitsPricingRouteImport
      parentRoute: typeof PropMgrUnitsRoute
    }
    '/prop-mgr/manage/$id': {
      id: '/prop-mgr/manage/$id'
      path: '/manage/$id'
      fullPath: '/prop-mgr/manage/$id'
      preLoaderRoute: typeof PropMgrManageIdRouteImport
      parentRoute: typeof PropMgrRoute
    }
    '/prop-mgr/finance/transactions': {
      id: '/prop-mgr/finance/transactions'
      path: '/transactions'
      fullPath: '/prop-mgr/finance/transactions'
      preLoaderRoute: typeof PropMgrFinanceTransactionsRouteImport
      parentRoute: typeof PropMgrFinanceRoute
    }
    '/portal/community/reviews': {
      id: '/portal/community/reviews'
      path: '/reviews'
      fullPath: '/portal/community/reviews'
      preLoaderRoute: typeof PortalCommunityReviewsRouteImport
      parentRoute: typeof PortalCommunityRoute
    }
    '/portal/community/events': {
      id: '/portal/community/events'
      path: '/events'
      fullPath: '/portal/community/events'
      preLoaderRoute: typeof PortalCommunityEventsRouteImport
      parentRoute: typeof PortalCommunityRoute
    }
    '/admin/leases/new': {
      id: '/admin/leases/new'
      path: '/new'
      fullPath: '/admin/leases/new'
      preLoaderRoute: typeof AdminLeasesNewRouteImport
      parentRoute: typeof AdminLeasesRoute
    }
    '/admin/finance/receipts': {
      id: '/admin/finance/receipts'
      path: '/receipts'
      fullPath: '/admin/finance/receipts'
      preLoaderRoute: typeof AdminFinanceReceiptsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/payables': {
      id: '/admin/finance/payables'
      path: '/payables'
      fullPath: '/admin/finance/payables'
      preLoaderRoute: typeof AdminFinancePayablesRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/ledger': {
      id: '/admin/finance/ledger'
      path: '/ledger'
      fullPath: '/admin/finance/ledger'
      preLoaderRoute: typeof AdminFinanceLedgerRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/coa': {
      id: '/admin/finance/coa'
      path: '/coa'
      fullPath: '/admin/finance/coa'
      preLoaderRoute: typeof AdminFinanceCoaRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
  }
}

interface AdminFinanceRouteChildren {
  AdminFinanceCoaRoute: typeof AdminFinanceCoaRoute
  AdminFinanceLedgerRoute: typeof AdminFinanceLedgerRoute
  AdminFinancePayablesRoute: typeof AdminFinancePayablesRoute
  AdminFinanceReceiptsRoute: typeof AdminFinanceReceiptsRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
}

const AdminFinanceRouteChildren: AdminFinanceRouteChildren = {
  AdminFinanceCoaRoute: AdminFinanceCoaRoute,
  AdminFinanceLedgerRoute: AdminFinanceLedgerRoute,
  AdminFinancePayablesRoute: AdminFinancePayablesRoute,
  AdminFinanceReceiptsRoute: AdminFinanceReceiptsRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
}

const AdminFinanceRouteWithChildren = AdminFinanceRoute._addFileChildren(
  AdminFinanceRouteChildren,
)

interface AdminLeasesRouteChildren {
  AdminLeasesNewRoute: typeof AdminLeasesNewRoute
}

const AdminLeasesRouteChildren: AdminLeasesRouteChildren = {
  AdminLeasesNewRoute: AdminLeasesNewRoute,
}

const AdminLeasesRouteWithChildren = AdminLeasesRoute._addFileChildren(
  AdminLeasesRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceRoute: typeof AdminFinanceRouteWithChildren
  AdminLeasesRoute: typeof AdminLeasesRouteWithChildren
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminMastersRoute: typeof AdminMastersRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminUnitsRoute: typeof AdminUnitsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceRoute: AdminFinanceRouteWithChildren,
  AdminLeasesRoute: AdminLeasesRouteWithChildren,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminMastersRoute: AdminMastersRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminUnitsRoute: AdminUnitsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CashierRouteChildren {
  CashierPdcRoute: typeof CashierPdcRoute
  CashierReceiptsRoute: typeof CashierReceiptsRoute
  CashierIndexRoute: typeof CashierIndexRoute
}

const CashierRouteChildren: CashierRouteChildren = {
  CashierPdcRoute: CashierPdcRoute,
  CashierReceiptsRoute: CashierReceiptsRoute,
  CashierIndexRoute: CashierIndexRoute,
}

const CashierRouteWithChildren =
  CashierRoute._addFileChildren(CashierRouteChildren)

interface FinanceRouteChildren {
  FinanceJournalRoute: typeof FinanceJournalRoute
  FinanceLedgerRoute: typeof FinanceLedgerRoute
  FinanceReceivablesRoute: typeof FinanceReceivablesRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceJournalRoute: FinanceJournalRoute,
  FinanceLedgerRoute: FinanceLedgerRoute,
  FinanceReceivablesRoute: FinanceReceivablesRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface LeasingRouteChildren {
  LeasingCreateRoute: typeof LeasingCreateRoute
  LeasingManageRoute: typeof LeasingManageRoute
  LeasingIndexRoute: typeof LeasingIndexRoute
}

const LeasingRouteChildren: LeasingRouteChildren = {
  LeasingCreateRoute: LeasingCreateRoute,
  LeasingManageRoute: LeasingManageRoute,
  LeasingIndexRoute: LeasingIndexRoute,
}

const LeasingRouteWithChildren =
  LeasingRoute._addFileChildren(LeasingRouteChildren)

interface MaintenanceRouteChildren {
  MaintenanceInventoryRoute: typeof MaintenanceInventoryRoute
  MaintenanceTicketsRoute: typeof MaintenanceTicketsRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
}

const MaintenanceRouteChildren: MaintenanceRouteChildren = {
  MaintenanceInventoryRoute: MaintenanceInventoryRoute,
  MaintenanceTicketsRoute: MaintenanceTicketsRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
}

const MaintenanceRouteWithChildren = MaintenanceRoute._addFileChildren(
  MaintenanceRouteChildren,
)

interface OwnerRouteChildren {
  OwnerApprovalsRoute: typeof OwnerApprovalsRoute
  OwnerDistributionsRoute: typeof OwnerDistributionsRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRoute
  OwnerStatementsRoute: typeof OwnerStatementsRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerApprovalsRoute: OwnerApprovalsRoute,
  OwnerDistributionsRoute: OwnerDistributionsRoute,
  OwnerPropertiesRoute: OwnerPropertiesRoute,
  OwnerStatementsRoute: OwnerStatementsRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface PortalCommunityRouteChildren {
  PortalCommunityEventsRoute: typeof PortalCommunityEventsRoute
  PortalCommunityReviewsRoute: typeof PortalCommunityReviewsRoute
}

const PortalCommunityRouteChildren: PortalCommunityRouteChildren = {
  PortalCommunityEventsRoute: PortalCommunityEventsRoute,
  PortalCommunityReviewsRoute: PortalCommunityReviewsRoute,
}

const PortalCommunityRouteWithChildren = PortalCommunityRoute._addFileChildren(
  PortalCommunityRouteChildren,
)

interface PortalRouteChildren {
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalCommunityRoute: typeof PortalCommunityRouteWithChildren
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalTicketsRoute: typeof PortalTicketsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookingsRoute: PortalBookingsRoute,
  PortalCommunityRoute: PortalCommunityRouteWithChildren,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalTicketsRoute: PortalTicketsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface PropMgrFinanceRouteChildren {
  PropMgrFinanceTransactionsRoute: typeof PropMgrFinanceTransactionsRoute
}

const PropMgrFinanceRouteChildren: PropMgrFinanceRouteChildren = {
  PropMgrFinanceTransactionsRoute: PropMgrFinanceTransactionsRoute,
}

const PropMgrFinanceRouteWithChildren = PropMgrFinanceRoute._addFileChildren(
  PropMgrFinanceRouteChildren,
)

interface PropMgrUnitsRouteChildren {
  PropMgrUnitsPricingRoute: typeof PropMgrUnitsPricingRoute
}

const PropMgrUnitsRouteChildren: PropMgrUnitsRouteChildren = {
  PropMgrUnitsPricingRoute: PropMgrUnitsPricingRoute,
}

const PropMgrUnitsRouteWithChildren = PropMgrUnitsRoute._addFileChildren(
  PropMgrUnitsRouteChildren,
)

interface PropMgrRouteChildren {
  PropMgrApprovalsRoute: typeof PropMgrApprovalsRoute
  PropMgrAssetsRoute: typeof PropMgrAssetsRoute
  PropMgrCreateRoute: typeof PropMgrCreateRoute
  PropMgrFinanceRoute: typeof PropMgrFinanceRouteWithChildren
  PropMgrLeasesRoute: typeof PropMgrLeasesRoute
  PropMgrLeasingRoute: typeof PropMgrLeasingRoute
  PropMgrMaintenanceRoute: typeof PropMgrMaintenanceRoute
  PropMgrPropertiesRoute: typeof PropMgrPropertiesRoute
  PropMgrUnitsRoute: typeof PropMgrUnitsRouteWithChildren
  PropMgrUsersRoute: typeof PropMgrUsersRoute
  PropMgrIndexRoute: typeof PropMgrIndexRoute
  PropMgrManageIdRoute: typeof PropMgrManageIdRoute
}

const PropMgrRouteChildren: PropMgrRouteChildren = {
  PropMgrApprovalsRoute: PropMgrApprovalsRoute,
  PropMgrAssetsRoute: PropMgrAssetsRoute,
  PropMgrCreateRoute: PropMgrCreateRoute,
  PropMgrFinanceRoute: PropMgrFinanceRouteWithChildren,
  PropMgrLeasesRoute: PropMgrLeasesRoute,
  PropMgrLeasingRoute: PropMgrLeasingRoute,
  PropMgrMaintenanceRoute: PropMgrMaintenanceRoute,
  PropMgrPropertiesRoute: PropMgrPropertiesRoute,
  PropMgrUnitsRoute: PropMgrUnitsRouteWithChildren,
  PropMgrUsersRoute: PropMgrUsersRoute,
  PropMgrIndexRoute: PropMgrIndexRoute,
  PropMgrManageIdRoute: PropMgrManageIdRoute,
}

const PropMgrRouteWithChildren =
  PropMgrRoute._addFileChildren(PropMgrRouteChildren)

interface SalesRouteChildren {
  SalesAppointmentsRoute: typeof SalesAppointmentsRoute
  SalesContractsRoute: typeof SalesContractsRoute
  SalesListingsRoute: typeof SalesListingsRoute
  SalesReservationsRoute: typeof SalesReservationsRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesAppointmentsRoute: SalesAppointmentsRoute,
  SalesContractsRoute: SalesContractsRoute,
  SalesListingsRoute: SalesListingsRoute,
  SalesReservationsRoute: SalesReservationsRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminBillingRoute: typeof SuperAdminBillingRoute
  SuperAdminConfigRoute: typeof SuperAdminConfigRoute
  SuperAdminNotificationsRoute: typeof SuperAdminNotificationsRoute
  SuperAdminPermissionsRoute: typeof SuperAdminPermissionsRoute
  SuperAdminSecurityRoute: typeof SuperAdminSecurityRoute
  SuperAdminTenantsRoute: typeof SuperAdminTenantsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminBillingRoute: SuperAdminBillingRoute,
  SuperAdminConfigRoute: SuperAdminConfigRoute,
  SuperAdminNotificationsRoute: SuperAdminNotificationsRoute,
  SuperAdminPermissionsRoute: SuperAdminPermissionsRoute,
  SuperAdminSecurityRoute: SuperAdminSecurityRoute,
  SuperAdminTenantsRoute: SuperAdminTenantsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CashierRoute: CashierRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  GuestRoute: GuestRoute,
  LeasingRoute: LeasingRouteWithChildren,
  MaintenanceRoute: MaintenanceRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PropMgrRoute: PropMgrRouteWithChildren,
  SalesRoute: SalesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
