/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as HostRouteImport } from './routes/host'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SalesReservationsRouteImport } from './routes/sales.reservations'
import { Route as SalesListingsRouteImport } from './routes/sales.listings'
import { Route as SalesContractsRouteImport } from './routes/sales.contracts'
import { Route as SalesAppointmentsRouteImport } from './routes/sales.appointments'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as PortalTicketsRouteImport } from './routes/portal.tickets'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalCommunityRouteImport } from './routes/portal.community'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'
import { Route as OwnerStatementsRouteImport } from './routes/owner.statements'
import { Route as OwnerPropertiesRouteImport } from './routes/owner.properties'
import { Route as OwnerDistributionsRouteImport } from './routes/owner.distributions'
import { Route as OwnerApprovalsRouteImport } from './routes/owner.approvals'
import { Route as HostUsersRouteImport } from './routes/host.users'
import { Route as HostUnitsRouteImport } from './routes/host.units'
import { Route as HostPropertiesRouteImport } from './routes/host.properties'
import { Route as HostMaintenanceRouteImport } from './routes/host.maintenance'
import { Route as HostLeasingRouteImport } from './routes/host.leasing'
import { Route as HostLeasesRouteImport } from './routes/host.leases'
import { Route as HostFinanceRouteImport } from './routes/host.finance'
import { Route as HostCreateRouteImport } from './routes/host.create'
import { Route as HostAssetsRouteImport } from './routes/host.assets'
import { Route as HostApprovalsRouteImport } from './routes/host.approvals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUnitsRouteImport } from './routes/admin.units'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminMastersRouteImport } from './routes/admin.masters'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminLeasesRouteImport } from './routes/admin.leases'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin.finance.index'
import { Route as PortalCommunityReviewsRouteImport } from './routes/portal.community.reviews'
import { Route as PortalCommunityEventsRouteImport } from './routes/portal.community.events'
import { Route as HostManageIdRouteImport } from './routes/host.manage.$id'
import { Route as HostFinanceTransactionsRouteImport } from './routes/host.finance.transactions'
import { Route as AdminFinanceReceiptsRouteImport } from './routes/admin.finance.receipts'
import { Route as AdminFinancePayablesRouteImport } from './routes/admin.finance.payables'
import { Route as AdminFinanceLedgerRouteImport } from './routes/admin.finance.ledger'
import { Route as AdminFinanceCoaRouteImport } from './routes/admin.finance.coa'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SalesReservationsRoute = SalesReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => SalesRoute,
} as any)
const SalesListingsRoute = SalesListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => SalesRoute,
} as any)
const SalesContractsRoute = SalesContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => SalesRoute,
} as any)
const SalesAppointmentsRoute = SalesAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => SalesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const PortalTicketsRoute = PortalTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCommunityRoute = PortalCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const OwnerStatementsRoute = OwnerStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDistributionsRoute = OwnerDistributionsRouteImport.update({
  id: '/distributions',
  path: '/distributions',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerApprovalsRoute = OwnerApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => OwnerRoute,
} as any)
const HostUsersRoute = HostUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => HostRoute,
} as any)
const HostUnitsRoute = HostUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => HostRoute,
} as any)
const HostPropertiesRoute = HostPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => HostRoute,
} as any)
const HostMaintenanceRoute = HostMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => HostRoute,
} as any)
const HostLeasingRoute = HostLeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => HostRoute,
} as any)
const HostLeasesRoute = HostLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => HostRoute,
} as any)
const HostFinanceRoute = HostFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => HostRoute,
} as any)
const HostCreateRoute = HostCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => HostRoute,
} as any)
const HostAssetsRoute = HostAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => HostRoute,
} as any)
const HostApprovalsRoute = HostApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => HostRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitsRoute = AdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMastersRoute = AdminMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeasesRoute = AdminLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const PortalCommunityReviewsRoute = PortalCommunityReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => PortalCommunityRoute,
} as any)
const PortalCommunityEventsRoute = PortalCommunityEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalCommunityRoute,
} as any)
const HostManageIdRoute = HostManageIdRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => HostRoute,
} as any)
const HostFinanceTransactionsRoute = HostFinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => HostFinanceRoute,
} as any)
const AdminFinanceReceiptsRoute = AdminFinanceReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinancePayablesRoute = AdminFinancePayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceLedgerRoute = AdminFinanceLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceCoaRoute = AdminFinanceCoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => AdminFinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/guest': typeof GuestRoute
  '/host': typeof HostRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/properties': typeof PropertiesRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/leases': typeof AdminLeasesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/host/approvals': typeof HostApprovalsRoute
  '/host/assets': typeof HostAssetsRoute
  '/host/create': typeof HostCreateRoute
  '/host/finance': typeof HostFinanceRouteWithChildren
  '/host/leases': typeof HostLeasesRoute
  '/host/leasing': typeof HostLeasingRoute
  '/host/maintenance': typeof HostMaintenanceRoute
  '/host/properties': typeof HostPropertiesRoute
  '/host/units': typeof HostUnitsRoute
  '/host/users': typeof HostUsersRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/owner/distributions': typeof OwnerDistributionsRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/community': typeof PortalCommunityRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/sales/appointments': typeof SalesAppointmentsRoute
  '/sales/contracts': typeof SalesContractsRoute
  '/sales/listings': typeof SalesListingsRoute
  '/sales/reservations': typeof SalesReservationsRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/finance/coa': typeof AdminFinanceCoaRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/finance/payables': typeof AdminFinancePayablesRoute
  '/admin/finance/receipts': typeof AdminFinanceReceiptsRoute
  '/host/finance/transactions': typeof HostFinanceTransactionsRoute
  '/host/manage/$id': typeof HostManageIdRoute
  '/portal/community/events': typeof PortalCommunityEventsRoute
  '/portal/community/reviews': typeof PortalCommunityReviewsRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/guest': typeof GuestRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leases': typeof AdminLeasesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/host/approvals': typeof HostApprovalsRoute
  '/host/assets': typeof HostAssetsRoute
  '/host/create': typeof HostCreateRoute
  '/host/finance': typeof HostFinanceRouteWithChildren
  '/host/leases': typeof HostLeasesRoute
  '/host/leasing': typeof HostLeasingRoute
  '/host/maintenance': typeof HostMaintenanceRoute
  '/host/properties': typeof HostPropertiesRoute
  '/host/units': typeof HostUnitsRoute
  '/host/users': typeof HostUsersRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/owner/distributions': typeof OwnerDistributionsRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/community': typeof PortalCommunityRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/sales/appointments': typeof SalesAppointmentsRoute
  '/sales/contracts': typeof SalesContractsRoute
  '/sales/listings': typeof SalesListingsRoute
  '/sales/reservations': typeof SalesReservationsRoute
  '/admin': typeof AdminIndexRoute
  '/host': typeof HostIndexRoute
  '/portal': typeof PortalIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/finance/coa': typeof AdminFinanceCoaRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/finance/payables': typeof AdminFinancePayablesRoute
  '/admin/finance/receipts': typeof AdminFinanceReceiptsRoute
  '/host/finance/transactions': typeof HostFinanceTransactionsRoute
  '/host/manage/$id': typeof HostManageIdRoute
  '/portal/community/events': typeof PortalCommunityEventsRoute
  '/portal/community/reviews': typeof PortalCommunityReviewsRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/contact': typeof ContactRoute
  '/guest': typeof GuestRoute
  '/host': typeof HostRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/properties': typeof PropertiesRouteWithChildren
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/leases': typeof AdminLeasesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/masters': typeof AdminMastersRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/host/approvals': typeof HostApprovalsRoute
  '/host/assets': typeof HostAssetsRoute
  '/host/create': typeof HostCreateRoute
  '/host/finance': typeof HostFinanceRouteWithChildren
  '/host/leases': typeof HostLeasesRoute
  '/host/leasing': typeof HostLeasingRoute
  '/host/maintenance': typeof HostMaintenanceRoute
  '/host/properties': typeof HostPropertiesRoute
  '/host/units': typeof HostUnitsRoute
  '/host/users': typeof HostUsersRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/owner/distributions': typeof OwnerDistributionsRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/community': typeof PortalCommunityRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/tickets': typeof PortalTicketsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/sales/appointments': typeof SalesAppointmentsRoute
  '/sales/contracts': typeof SalesContractsRoute
  '/sales/listings': typeof SalesListingsRoute
  '/sales/reservations': typeof SalesReservationsRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/finance/coa': typeof AdminFinanceCoaRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/finance/payables': typeof AdminFinancePayablesRoute
  '/admin/finance/receipts': typeof AdminFinanceReceiptsRoute
  '/host/finance/transactions': typeof HostFinanceTransactionsRoute
  '/host/manage/$id': typeof HostManageIdRoute
  '/portal/community/events': typeof PortalCommunityEventsRoute
  '/portal/community/reviews': typeof PortalCommunityReviewsRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-visit'
    | '/contact'
    | '/guest'
    | '/host'
    | '/owner'
    | '/portal'
    | '/properties'
    | '/sales'
    | '/sitemap.xml'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/leases'
    | '/admin/maintenance'
    | '/admin/masters'
    | '/admin/properties'
    | '/admin/units'
    | '/admin/users'
    | '/host/approvals'
    | '/host/assets'
    | '/host/create'
    | '/host/finance'
    | '/host/leases'
    | '/host/leasing'
    | '/host/maintenance'
    | '/host/properties'
    | '/host/units'
    | '/host/users'
    | '/owner/approvals'
    | '/owner/distributions'
    | '/owner/properties'
    | '/owner/statements'
    | '/portal/bookings'
    | '/portal/community'
    | '/portal/documents'
    | '/portal/payments'
    | '/portal/settings'
    | '/portal/tickets'
    | '/properties/$id'
    | '/sales/appointments'
    | '/sales/contracts'
    | '/sales/listings'
    | '/sales/reservations'
    | '/admin/'
    | '/host/'
    | '/portal/'
    | '/properties/'
    | '/admin/finance/coa'
    | '/admin/finance/ledger'
    | '/admin/finance/payables'
    | '/admin/finance/receipts'
    | '/host/finance/transactions'
    | '/host/manage/$id'
    | '/portal/community/events'
    | '/portal/community/reviews'
    | '/admin/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book-visit'
    | '/contact'
    | '/guest'
    | '/owner'
    | '/sales'
    | '/sitemap.xml'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/leases'
    | '/admin/maintenance'
    | '/admin/masters'
    | '/admin/properties'
    | '/admin/units'
    | '/admin/users'
    | '/host/approvals'
    | '/host/assets'
    | '/host/create'
    | '/host/finance'
    | '/host/leases'
    | '/host/leasing'
    | '/host/maintenance'
    | '/host/properties'
    | '/host/units'
    | '/host/users'
    | '/owner/approvals'
    | '/owner/distributions'
    | '/owner/properties'
    | '/owner/statements'
    | '/portal/bookings'
    | '/portal/community'
    | '/portal/documents'
    | '/portal/payments'
    | '/portal/settings'
    | '/portal/tickets'
    | '/properties/$id'
    | '/sales/appointments'
    | '/sales/contracts'
    | '/sales/listings'
    | '/sales/reservations'
    | '/admin'
    | '/host'
    | '/portal'
    | '/properties'
    | '/admin/finance/coa'
    | '/admin/finance/ledger'
    | '/admin/finance/payables'
    | '/admin/finance/receipts'
    | '/host/finance/transactions'
    | '/host/manage/$id'
    | '/portal/community/events'
    | '/portal/community/reviews'
    | '/admin/finance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-visit'
    | '/contact'
    | '/guest'
    | '/host'
    | '/owner'
    | '/portal'
    | '/properties'
    | '/sales'
    | '/sitemap.xml'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/leases'
    | '/admin/maintenance'
    | '/admin/masters'
    | '/admin/properties'
    | '/admin/units'
    | '/admin/users'
    | '/host/approvals'
    | '/host/assets'
    | '/host/create'
    | '/host/finance'
    | '/host/leases'
    | '/host/leasing'
    | '/host/maintenance'
    | '/host/properties'
    | '/host/units'
    | '/host/users'
    | '/owner/approvals'
    | '/owner/distributions'
    | '/owner/properties'
    | '/owner/statements'
    | '/portal/bookings'
    | '/portal/community'
    | '/portal/documents'
    | '/portal/payments'
    | '/portal/settings'
    | '/portal/tickets'
    | '/properties/$id'
    | '/sales/appointments'
    | '/sales/contracts'
    | '/sales/listings'
    | '/sales/reservations'
    | '/admin/'
    | '/host/'
    | '/portal/'
    | '/properties/'
    | '/admin/finance/coa'
    | '/admin/finance/ledger'
    | '/admin/finance/payables'
    | '/admin/finance/receipts'
    | '/host/finance/transactions'
    | '/host/manage/$id'
    | '/portal/community/events'
    | '/portal/community/reviews'
    | '/admin/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookVisitRoute: typeof BookVisitRoute
  ContactRoute: typeof ContactRoute
  GuestRoute: typeof GuestRoute
  HostRoute: typeof HostRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SalesRoute: typeof SalesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sales/reservations': {
      id: '/sales/reservations'
      path: '/reservations'
      fullPath: '/sales/reservations'
      preLoaderRoute: typeof SalesReservationsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/listings': {
      id: '/sales/listings'
      path: '/listings'
      fullPath: '/sales/listings'
      preLoaderRoute: typeof SalesListingsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/contracts': {
      id: '/sales/contracts'
      path: '/contracts'
      fullPath: '/sales/contracts'
      preLoaderRoute: typeof SalesContractsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/appointments': {
      id: '/sales/appointments'
      path: '/appointments'
      fullPath: '/sales/appointments'
      preLoaderRoute: typeof SalesAppointmentsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/portal/tickets': {
      id: '/portal/tickets'
      path: '/tickets'
      fullPath: '/portal/tickets'
      preLoaderRoute: typeof PortalTicketsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/community': {
      id: '/portal/community'
      path: '/community'
      fullPath: '/portal/community'
      preLoaderRoute: typeof PortalCommunityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/owner/statements': {
      id: '/owner/statements'
      path: '/statements'
      fullPath: '/owner/statements'
      preLoaderRoute: typeof OwnerStatementsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/distributions': {
      id: '/owner/distributions'
      path: '/distributions'
      fullPath: '/owner/distributions'
      preLoaderRoute: typeof OwnerDistributionsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/approvals': {
      id: '/owner/approvals'
      path: '/approvals'
      fullPath: '/owner/approvals'
      preLoaderRoute: typeof OwnerApprovalsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/host/users': {
      id: '/host/users'
      path: '/users'
      fullPath: '/host/users'
      preLoaderRoute: typeof HostUsersRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/units': {
      id: '/host/units'
      path: '/units'
      fullPath: '/host/units'
      preLoaderRoute: typeof HostUnitsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/properties': {
      id: '/host/properties'
      path: '/properties'
      fullPath: '/host/properties'
      preLoaderRoute: typeof HostPropertiesRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/maintenance': {
      id: '/host/maintenance'
      path: '/maintenance'
      fullPath: '/host/maintenance'
      preLoaderRoute: typeof HostMaintenanceRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/leasing': {
      id: '/host/leasing'
      path: '/leasing'
      fullPath: '/host/leasing'
      preLoaderRoute: typeof HostLeasingRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/leases': {
      id: '/host/leases'
      path: '/leases'
      fullPath: '/host/leases'
      preLoaderRoute: typeof HostLeasesRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/finance': {
      id: '/host/finance'
      path: '/finance'
      fullPath: '/host/finance'
      preLoaderRoute: typeof HostFinanceRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/create': {
      id: '/host/create'
      path: '/create'
      fullPath: '/host/create'
      preLoaderRoute: typeof HostCreateRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/assets': {
      id: '/host/assets'
      path: '/assets'
      fullPath: '/host/assets'
      preLoaderRoute: typeof HostAssetsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/approvals': {
      id: '/host/approvals'
      path: '/approvals'
      fullPath: '/host/approvals'
      preLoaderRoute: typeof HostApprovalsRouteImport
      parentRoute: typeof HostRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/units': {
      id: '/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AdminUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/masters': {
      id: '/admin/masters'
      path: '/masters'
      fullPath: '/admin/masters'
      preLoaderRoute: typeof AdminMastersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leases': {
      id: '/admin/leases'
      path: '/leases'
      fullPath: '/admin/leases'
      preLoaderRoute: typeof AdminLeasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/portal/community/reviews': {
      id: '/portal/community/reviews'
      path: '/reviews'
      fullPath: '/portal/community/reviews'
      preLoaderRoute: typeof PortalCommunityReviewsRouteImport
      parentRoute: typeof PortalCommunityRoute
    }
    '/portal/community/events': {
      id: '/portal/community/events'
      path: '/events'
      fullPath: '/portal/community/events'
      preLoaderRoute: typeof PortalCommunityEventsRouteImport
      parentRoute: typeof PortalCommunityRoute
    }
    '/host/manage/$id': {
      id: '/host/manage/$id'
      path: '/manage/$id'
      fullPath: '/host/manage/$id'
      preLoaderRoute: typeof HostManageIdRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/finance/transactions': {
      id: '/host/finance/transactions'
      path: '/transactions'
      fullPath: '/host/finance/transactions'
      preLoaderRoute: typeof HostFinanceTransactionsRouteImport
      parentRoute: typeof HostFinanceRoute
    }
    '/admin/finance/receipts': {
      id: '/admin/finance/receipts'
      path: '/receipts'
      fullPath: '/admin/finance/receipts'
      preLoaderRoute: typeof AdminFinanceReceiptsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/payables': {
      id: '/admin/finance/payables'
      path: '/payables'
      fullPath: '/admin/finance/payables'
      preLoaderRoute: typeof AdminFinancePayablesRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/ledger': {
      id: '/admin/finance/ledger'
      path: '/ledger'
      fullPath: '/admin/finance/ledger'
      preLoaderRoute: typeof AdminFinanceLedgerRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/coa': {
      id: '/admin/finance/coa'
      path: '/coa'
      fullPath: '/admin/finance/coa'
      preLoaderRoute: typeof AdminFinanceCoaRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
  }
}

interface AdminFinanceRouteChildren {
  AdminFinanceCoaRoute: typeof AdminFinanceCoaRoute
  AdminFinanceLedgerRoute: typeof AdminFinanceLedgerRoute
  AdminFinancePayablesRoute: typeof AdminFinancePayablesRoute
  AdminFinanceReceiptsRoute: typeof AdminFinanceReceiptsRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
}

const AdminFinanceRouteChildren: AdminFinanceRouteChildren = {
  AdminFinanceCoaRoute: AdminFinanceCoaRoute,
  AdminFinanceLedgerRoute: AdminFinanceLedgerRoute,
  AdminFinancePayablesRoute: AdminFinancePayablesRoute,
  AdminFinanceReceiptsRoute: AdminFinanceReceiptsRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
}

const AdminFinanceRouteWithChildren = AdminFinanceRoute._addFileChildren(
  AdminFinanceRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceRoute: typeof AdminFinanceRouteWithChildren
  AdminLeasesRoute: typeof AdminLeasesRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminMastersRoute: typeof AdminMastersRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminUnitsRoute: typeof AdminUnitsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceRoute: AdminFinanceRouteWithChildren,
  AdminLeasesRoute: AdminLeasesRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminMastersRoute: AdminMastersRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminUnitsRoute: AdminUnitsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HostFinanceRouteChildren {
  HostFinanceTransactionsRoute: typeof HostFinanceTransactionsRoute
}

const HostFinanceRouteChildren: HostFinanceRouteChildren = {
  HostFinanceTransactionsRoute: HostFinanceTransactionsRoute,
}

const HostFinanceRouteWithChildren = HostFinanceRoute._addFileChildren(
  HostFinanceRouteChildren,
)

interface HostRouteChildren {
  HostApprovalsRoute: typeof HostApprovalsRoute
  HostAssetsRoute: typeof HostAssetsRoute
  HostCreateRoute: typeof HostCreateRoute
  HostFinanceRoute: typeof HostFinanceRouteWithChildren
  HostLeasesRoute: typeof HostLeasesRoute
  HostLeasingRoute: typeof HostLeasingRoute
  HostMaintenanceRoute: typeof HostMaintenanceRoute
  HostPropertiesRoute: typeof HostPropertiesRoute
  HostUnitsRoute: typeof HostUnitsRoute
  HostUsersRoute: typeof HostUsersRoute
  HostIndexRoute: typeof HostIndexRoute
  HostManageIdRoute: typeof HostManageIdRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostApprovalsRoute: HostApprovalsRoute,
  HostAssetsRoute: HostAssetsRoute,
  HostCreateRoute: HostCreateRoute,
  HostFinanceRoute: HostFinanceRouteWithChildren,
  HostLeasesRoute: HostLeasesRoute,
  HostLeasingRoute: HostLeasingRoute,
  HostMaintenanceRoute: HostMaintenanceRoute,
  HostPropertiesRoute: HostPropertiesRoute,
  HostUnitsRoute: HostUnitsRoute,
  HostUsersRoute: HostUsersRoute,
  HostIndexRoute: HostIndexRoute,
  HostManageIdRoute: HostManageIdRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

interface OwnerRouteChildren {
  OwnerApprovalsRoute: typeof OwnerApprovalsRoute
  OwnerDistributionsRoute: typeof OwnerDistributionsRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRoute
  OwnerStatementsRoute: typeof OwnerStatementsRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerApprovalsRoute: OwnerApprovalsRoute,
  OwnerDistributionsRoute: OwnerDistributionsRoute,
  OwnerPropertiesRoute: OwnerPropertiesRoute,
  OwnerStatementsRoute: OwnerStatementsRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface PortalCommunityRouteChildren {
  PortalCommunityEventsRoute: typeof PortalCommunityEventsRoute
  PortalCommunityReviewsRoute: typeof PortalCommunityReviewsRoute
}

const PortalCommunityRouteChildren: PortalCommunityRouteChildren = {
  PortalCommunityEventsRoute: PortalCommunityEventsRoute,
  PortalCommunityReviewsRoute: PortalCommunityReviewsRoute,
}

const PortalCommunityRouteWithChildren = PortalCommunityRoute._addFileChildren(
  PortalCommunityRouteChildren,
)

interface PortalRouteChildren {
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalCommunityRoute: typeof PortalCommunityRouteWithChildren
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalTicketsRoute: typeof PortalTicketsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookingsRoute: PortalBookingsRoute,
  PortalCommunityRoute: PortalCommunityRouteWithChildren,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalTicketsRoute: PortalTicketsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

interface SalesRouteChildren {
  SalesAppointmentsRoute: typeof SalesAppointmentsRoute
  SalesContractsRoute: typeof SalesContractsRoute
  SalesListingsRoute: typeof SalesListingsRoute
  SalesReservationsRoute: typeof SalesReservationsRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesAppointmentsRoute: SalesAppointmentsRoute,
  SalesContractsRoute: SalesContractsRoute,
  SalesListingsRoute: SalesListingsRoute,
  SalesReservationsRoute: SalesReservationsRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookVisitRoute: BookVisitRoute,
  ContactRoute: ContactRoute,
  GuestRoute: GuestRoute,
  HostRoute: HostRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PropertiesRoute: PropertiesRouteWithChildren,
  SalesRoute: SalesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
